### ISSUE TITLE
Empty JSON File

### ISSUE THREAD

**Issue by benjaminhorner** [shama/grunt-minjson#3]
EDIT : this happens when paths are badly written (was my case. Sorry)/ However, no error is shown in the log during grunt task. Merge this with other Issue.

When running the task, all JSON minyfied JSON files are empty.
Tested with this JSON file contents : 
{
  "one": "Singular sensation",
  "two": "Beady little eyes",
  "three": "Little birds pitch by my doorstep"
}

**Comment by shama** [comment]
Closing as this should be fixed. Please reopen if it has not.
