### ISSUE TITLE
JSON5 vs JSON

### ISSUE THREAD

**Issue by brunomperes** [shama/grunt-minjson#8]
Hi @shama , 
After pushing #7, the outputted JSON seemed to be with the keys on the first depth without quotes on my input (no idea why), which was making my Angular application crash because it uses the standard JSON.stringify() instead of JSON5.

So I was wondering why using the JSON5, as it could generate JSONs that aren't supported on other applications. Perhaps parameterizing the usage of JSON5 in favor of the standard version of JSON or JSON3?

**Comment by shama** [comment]
Oh wow, could you gist an example JSON file that causes this so I can take a look? If JSON5 is generating invalid JSON that is totally a bug.

**Comment by brunomperes** [comment]
It seems that the problem is with json5 v0.4.0, see the [changelog](https://github.com/aseemk/json5/blob/master/CHANGELOG.md#v040-code-diff
). They now remove quotes on keys where possible. Something as this

    {"key":"value"}

will output as:

    {key:"value"}

**Comment by alebianco** [comment]
definitively an issue, the minified json have all keys unquoted and are unusable on most applications

**Comment by brunomperes** [comment]
@shama any update on that? I'm happy to send a PR moving back to the default JSON.stringify method

**Comment by shama** [comment]
+1 thank you @brunomperes!

**Comment by shama** [comment]
Closed by https://github.com/shama/grunt-minjson/commit/5180debb1badd2c6a74d3e8beb2e16dcc5e46cc5
